repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6  # Use the latest version of ruff-pre-commit
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]  # Automatically fix linting issues
    - id: ruff-format
