[project]
name = "tutreklama"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Anton Kokorin", email = "ant.kkrn@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "psycopg[binary]>=3.2.10",
    "python-dotenv>=1.1.1",
]
