# Generated by Django 5.2.6 on 2025-09-25 09:16

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tg_user_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="ID пользователя в Telegram"
                    ),
                ),
                (
                    "tg_chat_id",
                    models.BigIntegerField(
                        verbose_name="ID чата с пользователем в Telegram"
                    ),
                ),
                (
                    "username",
                    models.TextField(blank=True, null=True, verbose_name="Username"),
                ),
                (
                    "first_name",
                    django_cryptography.fields.encrypt(
                        models.TextField(verbose_name="Имя")
                    ),
                ),
                (
                    "last_name",
                    django_cryptography.fields.encrypt(
                        models.TextField(blank=True, null=True, verbose_name="Фамилия")
                    ),
                ),
                (
                    "is_tg_premium",
                    models.BooleanField(default=False, verbose_name="Премиум?"),
                ),
                (
                    "phone_number",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            blank=True,
                            help_text="Появляется после того, как пользователь согласился предоставить свой контакт",
                            max_length=20,
                            null=True,
                            verbose_name="Номер телефона",
                        )
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Язык телеграма у пользователя",
                        max_length=10,
                        null=True,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "contact_given",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата предоставления контакта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активен"), ("banned", "Забанил")],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата смены статуса"
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Устанавливается при переходе по реферальной ссылке",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="bot.user",
                        verbose_name="Пригласивший пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
