# Generated by Django 5.2.6 on 2025-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_channel_userbot_channeluser_channel_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ключ текста"
                    ),
                ),
                (
                    "default_text",
                    models.TextField(verbose_name="Текст по умолчанию"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон текста",
                "verbose_name_plural": "Шаблоны текста",
            },
        ),
    ]
