# Generated by Django 5.2.6 on 2025-10-09 12:03

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_texttemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelnews",
            name="short_message",
            field=utils.models.TruncatingCharField(blank=True, max_length=150),
        ),
    ]
