# Generated by Django 5.2.6 on 2025-10-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_allow_null_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelnews",
            name="short_message",
        ),
    ]
