# Generated by Django 5.2.6 on 2025-10-13 15:49

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_remove_channelnews_short_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbot",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, help_text="Последняя активность", null=True
            ),
        ),
        migrations.AddField(
            model_name="userbot",
            name="last_error",
            field=models.TextField(blank=True, help_text="Последняя ошибка"),
        ),
        migrations.AddField(
            model_name="userbot",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive", "Неактивен"),
                    ("authorizing", "Авторизуется"),
                    ("active", "Активен"),
                    ("error", "Ошибка"),
                ],
                default="inactive",
                help_text="Статус юзербота",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userbot",
            name="string_session",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True, help_text="String session для авторизации")
            ),
        ),
        migrations.AlterField(
            model_name="userbot",
            name="session_file",
            field=models.CharField(
                default="", help_text="Путь к .session (Telethon)", max_length=255
            ),
        ),
    ]
