# Generated by Django 5.2.6 on 2025-10-13 16:11

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_userbot_last_activity_userbot_last_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbot",
            name="string_session",
            field=django_cryptography.fields.encrypt(
                models.TextField(
                    blank=True,
                    help_text="String session для авторизации",
                    null=True,
                )
            ),
        ),
    ]
