# Generated by Django 5.2.7 on 2025-10-20 11:30

from django.db import migrations


def create_initial_tariffs(apps, schema_editor):
    Tariff = apps.get_model("bot", "Tariff")

    if Tariff.objects.exists():
        return

    Tariff.objects.create(
        name="Базовый",
        price=690,
        duration_days=30,
        channels_limit=15,
        is_active=True,
        description="Стартовый план на 30 дней",
    )

    Tariff.objects.create(
        name="Премиум",
        price=1490,
        duration_days=30,
        channels_limit=60,
        is_active=True,
        description="Расширенный план на 30 дней",
    )

    Tariff.objects.create(
        name="Бизнес",
        price=2490,
        duration_days=30,
        channels_limit=50,
        is_active=True,
        description="Максимальный план на 30 дней",
    )

    Tariff.objects.create(
        name="Максимальный",
        price=4990,
        duration_days=30,
        channels_limit=100,
        is_active=True,
        description="Максимальный план на 30 дней",
    )


def delete_initial_tariffs(apps, schema_editor):
    Tariff = apps.get_model("bot", "Tariff")
    Tariff.objects.filter(
        name__in=["Базовый", "Премиум", "Бизнес", "Максимальный"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_tariff_usersubscription_payment_and_more"),
    ]

    operations = [
        migrations.RunPython(create_initial_tariffs, delete_initial_tariffs),
    ]
