# Generated by Django 5.2.7 on 2025-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0009_seed_initial_tariffs"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="is_recurring_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Включена ли автоплатеж для данной подписки",
                verbose_name="Автопродление включено",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="robokassa_invoice_id",
            field=models.PositiveIntegerField(
                help_text="Уникальный идентификатор инвойса в системе Robokassa (1-2147483647)",
                unique=True,
                verbose_name="ID инвойса Robokassa",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("expired", "Истекла"),
                    ("cancelled", "Отменена"),
                    ("unpaid", "Неоплачена"),
                ],
                default="active",
                max_length=20,
                verbose_name="Статус подписки",
            ),
        ),
    ]
