# Generated by Django 5.2.7 on 2025-10-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0010_usersubscription_is_recurring_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="previous_subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Ссылка на предыдущую подписку для рекуррентных платежей",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_subscriptions",
                to="bot.usersubscription",
                verbose_name="Предыдущая подписка",
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="robokassa_invoice_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Уникальный идентификатор инвойса в системе Robokassa (1-2147483647)",
                unique=True,
                verbose_name="ID инвойса Robokassa",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
