# Generated by Django 5.2.7 on 2025-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0012_remove_usersubscription_previous_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_master",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Первый платеж в цепочке рекуррентных платежей",
                verbose_name="Материнский платеж",
            ),
        ),
    ]
