# Generated by Django 5.2.7 on 2025-11-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0013_payment_is_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ads_campaign",
            field=models.CharField(
                blank=True,
                help_text="Рекламная кампания, по которой пришел пользователь",
                max_length=255,
                null=True,
                verbose_name="Рекламная кампания",
            ),
        ),
    ]
